IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Cameras' AND COLUMN_NAME = 'PermissionCamera')
BEGIN
    ALTER TABLE Cameras ADD PermissionCamera BIGINT NOT NULL DEFAULT 0;
END;