IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Sequences' AND COLUMN_NAME = 'Name' AND CHARACTER_MAXIMUM_LENGTH < 500)
BEGIN
    ALTER TABLE Sequences ALTER COLUMN Name NVARCHAR(500) NOT NULL;
END;