IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TemplateProcesses' AND COLUMN_NAME = 'AgentId')
BEGIN
    ALTER TABLE TemplateProcesses ADD AgentId BIGINT NULL;
END

ALTER TABLE TemplateProcesses
ADD CONSTRAINT FK_TemplateProcesses_Agents
FOREIGN KEY (AgentId) REFERENCES Agents(Id) ON DELETE SET NULL;
