@LiveView.WebApi_HostAddress = https://localhost:44326

GET {{LiveView.WebApi_HostAddress}}/api/cameras/
Accept: application/json

###

GET {{LiveView.WebApi_HostAddress}}/api/grids/
Accept: application/json

###

GET {{LiveView.WebApi_HostAddress}}/api/sequences/
Accept: application/json

###

GET {{LiveView.WebApi_HostAddress}}/api/servers/
Accept: application/json

###

GET {{LiveView.WebApi_HostAddress}}/api/templates/
Accept: application/json

###
